---
name: justbases CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # MANDATORY CHECKS THAT USE TOX
  tox-checks:
    strategy:
      matrix:
        task: [lint, test, coverage]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Install dependencies
        run: |
          pip3 install tox==3.15.2
      - name: Run test
        run: make -f Makefile ${{ matrix.task }}

  development_environment_checks:
    strategy:
      matrix:
        include:
          - dependencies: black python3-isort
            task: fmt-travis
          - dependencies: yamllint
            task: yamllint
    runs-on: ubuntu-latest
    container: fedora:35  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: Run tests
        run: make -f Makefile ${{ matrix.task }}
